# Generated by Django 5.1.9 on 2025-09-02 18:45

import adl_earthnetworks_plugin.validators
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0024_alter_hourlyobsagg_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthNetworksConnection',
            fields=[
                ('networkconnection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.networkconnection')),
            ],
            options={
                'verbose_name': 'EarthNetworks Data Connection',
                'verbose_name_plural': 'EarthNetworks Data Connections',
            },
            bases=('core.networkconnection',),
        ),
        migrations.CreateModel(
            name='EarthNetworksStationLink',
            fields=[
                ('stationlink_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.stationlink')),
                ('en_station_id', models.CharField(max_length=255, verbose_name='EarthNetworks Station ID')),
                ('start_date', models.DateTimeField(blank=True, help_text='The date to start collection data for the first collection. Ignored if any data has been collected already for this station', null=True, validators=[adl_earthnetworks_plugin.validators.validate_start_date], verbose_name='Initial Collection start date')),
            ],
            options={
                'verbose_name': 'EarthNetworks Station Link',
                'verbose_name_plural': 'EarthNetworks Stations Link',
            },
            bases=('core.stationlink',),
        ),
        migrations.CreateModel(
            name='EarthNetworksVariableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('en_variable', models.CharField(max_length=255, verbose_name='EarthNetworks Variable')),
                ('adl_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataparameter', verbose_name='ADL Parameter')),
                ('connection', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_mappings', to='adl_earthnetworks_plugin.earthnetworksconnection')),
                ('en_parameter_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit', verbose_name='EarthNetworks Parameter Unit')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
